name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependences (Tesseract + languages)
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-spa

      - name: Install Python dependences
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Smoke Test
        working-directory: examples
        run: |
          python - << 'PY'
          import os, sys
          sys.path.insert(0, os.path.abspath('..'))
          from main import load_appointments
          input_dir = "repo_screenshot_miCitaPrevia"
          load_appointments(input_dir)
          for f in ["REGISTRO.csv", "CITAS.csv", "CENTROMEDICO.csv", "Appointments.json"]:
              assert os.path.exists(f), f"Missing output: {f}"
          print("✅ Smoke Test passed successfully!")
          PY